### PR TITLE
fix multi GPU streams handling and default stream

### LINKED ISSUE #182: Problem with multi-Gpu single CPU kernel with CUPLA
Hello,

I am trying to use CUPLA for multi-GPU single CPU architecture. Below is the code. 
It works with a single GPU but not with more than one. 

#################################################

```C++
struct testBla{

    template<typename T_Acc> ALPAKA_FN_ACC void operator()(T_Acc const &acc, int* bla) const
    {
       *bla = 11;
        printf("Value %d\n", bla);

        return;
    }
};

int main()
{

    int ngpus;
    cudaGetDeviceCount(&ngpus);

    std::vector< int* > bla;
    bla.resize(ngpus);

    for (int idGpu=0; idGpu<ngpus; ++idGpu)
    {
     	cuplaSetDevice (idGpu);

        cuplaMalloc ((void**) &bla[idGpu], sizeof(int) );
        CUPLA_KERNEL_OPTI(testBla)(1,1)(bla[idGpu]);
        cuplaDeviceSynchronize();
    }

    for (int idGpu=0; idGpu<ngpus; ++idGpu)
    {
	cuplaSetDevice (idGpu);
	cuplaDeviceSynchronize();
    }


     for (int i=0; i<ngpus; ++i)
     {
        cuplaSetDevice (i);
        cudaDeviceReset();
     }

    return 0;

}
```
############################

This is the runtime error:

terminate called after throwing an instance of 'std::runtime_error'
  what():  /home/rodrig17/gpu-collision-simulation/cupla/alpaka/include/alpaka/queue/cuda_hip/QueueUniformCudaHipRtBase.hpp(75) 'cudaStreamCreateWithFlags( &m_UniformCudaHipQueue, 0x01)' returned error  : 'cudaErrorMemoryAllocation': 'out of memory'!
srun: error: kepler021: task 0: Aborted

#######################

This is the ccmake config:

ALPAKA_ACC_CPU_BT_OMP4_ENABLE    OFF                                                                                                                                                                      
 ALPAKA_ACC_CPU_B_OMP2_T_SEQ_EN   OFF                                                                                                                                                                      
 ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_   OFF                                                                                                                                                                      
 ALPAKA_ACC_CPU_B_SEQ_T_OMP2_EN   OFF                                                                                                                                                                      
 ALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENA   OFF                                                                                                                                                                      
 ALPAKA_ACC_CPU_B_SEQ_T_THREADS   OFF                                                                                                                                                                      
 ALPAKA_ACC_CPU_B_TBB_T_SEQ_ENA   OFF                                                                                                                                                                      
 ALPAKA_ACC_GPU_CUDA_ENABLE	  ON                                                                                                                                                                       
 ALPAKA_ACC_GPU_CUDA_ONLY_MODE    ON                                                                                                                                                                       
 ALPAKA_ACC_GPU_HIP_ENABLE        OFF                                                                                                                                                                      
 ALPAKA_ACC_GPU_HIP_ONLY_MODE     OFF                                                                                                                                                                      
 ALPAKA_CUDA_ARCH                 30                                                                                                                                                                       
 ALPAKA_CUDA_COMPILER             nvcc                                                                                                                                                                     
 ALPAKA_CUDA_FAST_MATH            ON                                                                                                                                                                       
 ALPAKA_CUDA_FTZ                  OFF                                                                                                                                                                      
 ALPAKA_CUDA_KEEP_FILES           OFF                                                                                                                                                                      
 ALPAKA_CUDA_NVCC_EXPT_EXTENDED   ON                                                                                                                                                                       
 ALPAKA_CUDA_NVCC_SEPARABLE_COM   OFF                                                                                                                                                                      
 ALPAKA_CUDA_SHOW_CODELINES	  OFF                                                                                                                                                                      
 ALPAKA_CUDA_SHOW_REGISTER        OFF                                                                                                                                                                      
 ALPAKA_CXX_STANDARD              14                                                                                                                                                                       
 ALPAKA_DEBUG                     0                                                                                                                                                                        
 ALPAKA_EMU_MEMCPY3D              OFF                                                                                                                                                                      
 ALPAKA_HIP_PLATFORM              nvcc                                                                                                                                                                     
 BUILD_APPS                       ON                                                                                                                                                                       
 BUILD_GMOCK                      ON                                                                                                                                                                       
 BUILD_GTEST                      OFF                                                                                                                                                                      
 BUILD_SHARED_LIBS                OFF                                                                                                                                                                      
 CMAKE_BUILD_TYPE                                                                                                                                                                                          
 CMAKE_CUDA_HOST_COMPILER                                                                                                                                                                                  
 CMAKE_INSTALL_PREFIX             /usr/local                                                                                                                                                               
 COMPILER_WARNINGS                -W;-Wall;-Wno-unused;-Wextra;-Wno-variadic-macros                                                                                                                        
 CUDA_HOST_COMPILER                                                                                                                                                                                        
 CUDA_SDK_ROOT_DIR                CUDA_SDK_ROOT_DIR-NOTFOUND                                                                                                                                               
 CUDA_TOOLKIT_ROOT_DIR            /trinity/shared/pkg/devel/cuda/10.0                                                                                                                                      
 CUDA_USE_STATIC_CUDA_RUNTIME     ON                                                                                                                                                                       
 CUDA_rt_LIBRARY                  /usr/lib64/librt.so                                                                                                                                                      
 CUPLA_STREAM_ASYNC_ENABLE        ON                                                                                                                                                                       
 NO_DECREMENT_DEPRECATED_WARNIN   OFF                                                                                                                                                                      
 OPENMESH_BENCHMARK_DIR                                                                                                                                                                                    
 OPENMESH_DOCS                    ON                                                                                                                                                                       
 OPENMESH_LIBRARY_DIR             /home/rodrig17/gpu-collision-simulation/build/Build/lib                                                                                                                  
 RT_LIBRARY                       /usr/lib64/librt.so                                                                                                                                                      
 STL_VECTOR_CHECKS                OFF                                                                                                                                                                      
 cupla_DIR                        /home/rodrig17/gpu-collision-simulation/cupla                                                                                                                            
 gmock_build_tests                OFF                                                                                                                                                                      
 gtest_build_samples              OFF                                                                                                                                                                      
 gtest_build_tests                OFF                                                                                                                                                                      
 gtest_disable_pthreads           OFF                                                                                                                                                                      

Thanks for any help!

### PR DESCRIPTION
**Pull request by psychocoderHPC**
fix #182

The handling of the default stream and the cupla internal enumaration of
streams created a invinite loop if more than one device was used.

### CODE REVIEW

File: include/cupla/manager/Stream.hpp [hunk 1]
```diff
@@ -165,7 +147,27 @@ namespace manager
...
+        {
+
+            auto& device = Device< DeviceType >::get();
+
+            std::unique_ptr<
+                QueueType
+            > streamPtr(
+                new QueueType(
+                    device.current()
+                )
```
Comment (sbastrakov) [inline include/cupla/manager/Stream.hpp:162]: `std::make_unique` is in C++14.

Comment (psychocoderHPC) [reply include/cupla/manager/Stream.hpp]: I update it, it was code from c++11 times.
